default: &default
  adapter: postgresql
  host: 127.0.0.1
  database: 'lemmoney'
  username: lemmoney
  password: lemmoney
  encoding: utf8
  reconnect: true
  port: 5432
  pool: 15
  timeout: 5000

development:
  <<: *default
  database: 'lemmoney_development'

test:
  <<: *default
  database: 'lemmoney_test'

production:
  <<: *default
  database: 'lemmoney_production'
